CREATE SEQUENCE CURSO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INSCRIPCION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RESUMEN_MQ_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CURSOS (
    ID NUMBER(19) PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL,
    INSTRUCTOR VARCHAR2(120) NOT NULL,
    DURACION VARCHAR2(80) NOT NULL,
    COSTO NUMBER(12, 2) NOT NULL
);

CREATE TABLE INSCRIPCIONES (
    ID NUMBER(19) PRIMARY KEY,
    ESTUDIANTE_NOMBRE VARCHAR2(120) NOT NULL,
    ESTUDIANTE_EMAIL VARCHAR2(120) NOT NULL,
    TOTAL NUMBER(12, 2) NOT NULL,
    FECHA_INSCRIPCION TIMESTAMP NOT NULL
);

CREATE TABLE INSCRIPCION_CURSOS (
    INSCRIPCION_ID NUMBER(19) NOT NULL,
    CURSO_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_INSCRIPCION_CURSOS PRIMARY KEY (INSCRIPCION_ID, CURSO_ID),
    CONSTRAINT FK_INSCRIPCION_CURSO_INS FOREIGN KEY (INSCRIPCION_ID) REFERENCES INSCRIPCIONES(ID),
    CONSTRAINT FK_INSCRIPCION_CURSO_CUR FOREIGN KEY (CURSO_ID) REFERENCES CURSOS(ID)
);

CREATE TABLE RESUMENES_INSCRIPCION_MQ (
    ID NUMBER(19) PRIMARY KEY,
    NUMERO_RESUMEN NUMBER(19) NOT NULL,
    ESTUDIANTE_NOMBRE VARCHAR2(120) NOT NULL,
    ESTUDIANTE_EMAIL VARCHAR2(120) NOT NULL,
    FECHA_INSCRIPCION TIMESTAMP NOT NULL,
    TOTAL NUMBER(12, 2) NOT NULL,
    CONTENIDO_RESUMEN CLOB NOT NULL,
    FECHA_PROCESAMIENTO TIMESTAMP NOT NULL
);
